from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from .views import BookList, BookViewSet

# Create a router instance.
router = DefaultRouter()
# Register the BookViewSet with the router.
# This automatically generates URLs for all CRUD operations.
router.register(r'books_all', BookViewSet, basename='book_all')

# URL patterns for the API app.
urlpatterns = [
    # Route for the BookList view (ListAPIView).
    path('books/', BookList.as_view(), name='book-list'),

    # This line includes all the URL patterns generated by the router.
    path('', include(router.urls)),

    # New path for obtaining an authentication token.
    # Users can POST their username and password to this endpoint.
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]